# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-change-app
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: udacityy
