apiVersion: v1
kind: Service
metadata:
  name: make-change-app-service
spec:
  selector:
    app: make-change-app
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: make-change-app
spec:
  selector:
    matchLabels:
      app: make-change-app
  replicas: 3
  template:
    metadata:
      labels:
        app: make-change-app
    spec:
      containers:
      - name: flask-change
        image: ismafin/make-change-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
