
apiVersion: v1
kind: Service
metadata:
  name: make-change-app-service
spec:
  selector:
    app: make-change-app
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: make-change-app
  labels:
    app: make-change-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: make-change-app
  template:
    metadata:
      labels:
        app: make-change-app
    spec:
      containers:
      - name: make-change-app
        image: ismafin/make-change-app:latest
        ports:
        - containerPort: 8080
