apiVersion: v1
kind: Service
metadata:
  name: hello-flask-change-service
spec:
  selector:
    app: hello-python-udacity-capstone
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python-udacity-capstone
spec:
  selector:
    matchLabels:
      app: hello-python-udacity-capstone
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-python-udacity-capstone
    spec:
      containers:
      - name: flask-change
        image: flask-change:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
